### PR TITLE
Add grid function to show axes grid

### PR DESCRIPTION
**Pull request by banesullivan**
I recently added functionality to highly control the bounds axes. 

This adds a method to plotter objects called `grid` that will display the grid behind the axes much like `matplolib`. This is simply a wrapped call to `add_bounds_axes` where the default parameters are edited.

Todo:

- [ ] Is it possible to show axes labels on ALL outer triads? The way it is shown below only shows closes outer triad. ParaView has this ability but I'm not sure how they implemented it...

**Example:**

```py
import vtki
from vtki import examples

vtki.set_plot_theme('doc')

data = examples.load_uniform()

tool = vtki.OrthogonalSlicer(data)

tool.plotter.add_mesh(data.threshold(200))

tool.plotter.grid()

```

grid

### CODE REVIEW

**Comment by akaszynski** [comment]
If you'd like to have labels around all triads:
```python
cubeAxesActor.SetFlyModeToStaticEdges()
```
I agree that we might want to add this as another option.

**Comment by banesullivan** [comment]
I have `SetFlyModeToStaticEdges()` implemented through the `location='all'` argument on `add_bounds_axes`.

But ParaView has a really nice configuration where the outer-front triads are labeled and not the back implemented through the `Label Unique Edges Only` option. Any idea how we might do that with a `vtkCubeAxesActor`?

From ParaView:
screen shot 2019-02-11 at 2 12 04 pm

**Comment by akaszynski** [comment]
As far as I can tell based on the online vtk documentation, this is only possible by making two actors.  In fact, you can tell that it's two actors in Paraview since the boundary edges are a different color than the grid edges.

I've made the necessary changes to the master branch, including updating both actors when updating the bounds.  I also changed the name from ``grid`` to ``show_grid``, and I'm not sure what you think about that.  I don't want it to be confused with the ``UnstructuredGrid`` or ``StructuredGrid`` objects, but maybe it's not too confusing.

Also, appveyor is getting on my nerves and I'm considering dropping it from the tests.  I use it for my other projects as it's necessary to build wheels for windows, but here it keeps getting locked up on build, generally due to PyQt and bluetooth drivers on Windows Server.  What do you think?

**Comment by banesullivan** [comment]
Ohh wait I think there was a miss communication in what I was looking for.  In the photo I post above from ParaView, the white outline is just an outline representation of the original dataset that I threshold so I could see the full data extents and not just the range around around the new thresholded data. 

I’m looking for a way to label the 6 edges that are labeled in that photo such that the very front and very back triads are not labeled.

Also to get the effect that two cube axes actor provide, it may be easier just to add an outline from the `outline` or `outline_corners` filter so we don’t have to manage several actors when a user wants to update the color, ticks, etc.

**Comment by akaszynski** [comment]
I see it now.  I’ll edit it.

**Comment by banesullivan** [comment]
Also, note that the plotter keeps track of the bounds so perhaps we could use a `vtkBoundingBox` instead of a second cube axes actor with an `add_buounding_box` function or something.

**Comment by banesullivan** [comment]
@akaszynski:

> Also, appveyor is getting on my nerves and I'm considering dropping it from the tests. I use it for my other projects as it's necessary to build wheels for windows, but here it keeps getting locked up on build, generally due to PyQt and bluetooth drivers on Windows Server. What do you think?

As much as I strongly dislike appveyor and think it stymies development (*typically takes 5x-10x longer than Travis, generally buggy because it's windows, and difficult to manage dependencies again because it's windows*), **I think we still need to keep the builds going there.**

I don't use windows computers and sometimes need appveyor to run the tests to make sure subtle differences on the VTK side for windows aren't broken. **To address issues with AppVeyor, how about we make it a non-required check for PRs?**

Moving forward I definitely want appveyor to run the full testing suite with similar coverage as Travis to help me develop features that don't just work on Mac and Linux.

*Perhaps you could give me maintainer access to appveyor so I can cancel builds and try to cleanup everything going on there? I realize I am usually the culprit of building up the backlog of failing builds on there... I do this to see which commits break what tests on Windows to help me develop bit faster, but appveyor cannot keep up if someone isn't actively canceling the failing builds that are backlogged.*

**Comment by banesullivan** [comment]
I went ahead and changed the bounding box feature to use a `vtkOutlineSource` so that several cube axes actors do not have to be managed

Example:

```py
import vtki
from vtki import examples

p = vtki.Plotter()
data = examples.load_uniform()
p.add_mesh(data.points)

p.add_bounds_axes(location='outer', grid=True)
p.add_bounding_box()

p.show()

```

**Comment by banesullivan** [comment]
Much of these changes already appear in the master branch so I'm merging it.

**Pull request merged**
