### PR TITLE
Add shortcut-keys for Linux.

### PR DESCRIPTION
**Pull request by prisae**

### CODE REVIEW

**Comment by prisae** [comment]
After some discussions with @banesullivan. There are probably also Mac-keys for 3D and 2D rotation, please add them. I suspect that Windows/Linux shortcuts are the same, but cannot test the Windows ones.

**Comment by banesullivan** [comment]
Awesome, thanks for investigating this @prisae! 

Down the road we can hopefully add more `vtki` specific keyboard shortcuts like screenshotting, probing datasets, etc.

**Comment by akaszynski** [comment]
Thanks for the addition!

**Comment by prisae** [comment]
> Thanks for the addition!

Thanks for `vtki`!

**Pull request merged**
