### PR TITLE
BUGFIX: PolyData init from just vertices was not setting the vertex cells

### PR DESCRIPTION
**Pull request by banesullivan**
@akaszynski, please double check this.

When constructing poly data that only has vertices, you must use `vtk.vtkPolyData.SetVerts`. Previously the code only used `vtk.vtkPolyData.SetPolys` which works when there are faces present.

## Code to Reproduce:

```py
import vtki
import numpy as np

points = np.array([[0, 0, 0],
                     [1, 0, 0],
                     [1, 1, 0],
                     [0, 1, 0],
                     [0.5, 0.5, -1]])

mesh = vtki.PolyData(points)
assert mesh.n_points == points.shape[0]
assert mesh.n_cells == points.shape[0]
mesh.plot(psize=10)
```

which would not have any vertices:

bad

### The fix

Now the vertices are properly set:

good

### CODE REVIEW

**Comment by akaszynski** [comment]
That’s correct.  If you wanted to make a point cloud in vtk in the past you’d have to construct a face array as well.  This is a good fix.

**Comment by banesullivan** [comment]
Would you mind pushing a patch release (v0.15.1) for this ASAP?

**Comment by akaszynski** [comment]
Just tagged and pushed.  Travis will upload soon.

**Comment by banesullivan** [comment]
Thank you!!!!!

**Comment by akaszynski** [comment]
Forgot to bump the version.  One second...

**Comment by akaszynski** [comment]
0.15.1 is live on [PyPi](https://pypi.org/project/vtki/)

**Comment by banesullivan** [comment]
Thanks for doing that on short notice, @akaszynski! I gave a brief introduction to using `vtki` with geoscience datasets and pairing it with `PVGeo` today that went really well! I'm hoping to gain a bit more traction bringing geoscientists to `vtki` before long.

Also, you might be interested to see an offshoot project I put together the other day to show off what's possible for geoscience datasets/formats via `vtki`: 

> [3D visualization for the Open Mining Format Python package (omf)](https://github.com/OpenGeoVis/omfvtk)

**Pull request merged**
