### PR TITLE
Refactor Keyword Arguments

### PR DESCRIPTION
**Pull request by banesullivan**
This is a pretty major refactoring of keyword arguments. @akaszynski: you may have issues with projects that have `vtki` as a dependency.  This may still need some refining so this can totally sit for a bit.

I view this as a necessary refactor that ensures all keyword arguments for plotting are consistent across `vtki` and adhere to many of the conventions in `matplotlib` to bring a level of familiarity to new users.

- [MatPlotLib Plotting kwargs](https://matplotlib.org/2.1.1/api/_as_gen/matplotlib.pyplot.plot.html)
- [MatPlotLib Text kwargs](https://matplotlib.org/api/text_api.html#matplotlib.text.Text)

**Example of fixing `vtki` consistency:** 

- the argument to control the size of points was inconsistently `psize` and `pointsize`. Now it is `pointsize` which follows conventions in `matplotlib`

- Arguments starting with `show`. Now they all start with `show_` (previously only some did)

**Examples of switching to `matplotlib` convention:**

- `colormap` -> `cmap`
- `xtitle` -> `xlabel`, `ytitle` -> `ylabel`, `ztitle` -> `zlabel`, 

### Some That Might Still Need Refactoring:

- `interpolatebeforemap`
- `use_2dmode`
- Should we make all arguments follow snake case?
   - `textcolor` -> `text_color`, etc.?

### CODE REVIEW

**Comment by akaszynski** [comment]
This has been on my mind for a while as part of this package wasn’t developed with PEP8 in mind.  Feel free to refactor, and I’ll update my dependancies.

Parameters like showedges and textcolor should also be refactored to snakecase.

**Comment by banesullivan** [comment]
Should we go for snake case on all arguments to be super consistent? 

- pointsize -> point_size
- linewidth -> line_width
- etc.

**Comment by akaszynski** [comment]
Yes.  I’ll keep this pull request until you’re done.  That way I only have to refactor once.

**Comment by banesullivan** [comment]
I think I got them all...

**Comment by akaszynski** [comment]
Thanks for making it matplotlib and pep8 consistent.  I’ll tag a 0.16.0 release soon as this is a major change to the API.

**Pull request merged**
